baseURL: "https://zihanzhang.me/"
title: Zihan Zhang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
#        - name: Books
#          url: books/
#          weight: 5 
        - name: Research
          url: research/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
        - name: ARE 201
          url: are201/
          weight: 4
#        - name: Data
#          url: data/
#          weight: 4
        - name: Math Camp
          url: mathcamp/
          weight: 5

params:
    description: "Zihan Zhang — Economics PhD student at North Carolina State University. Research interests in international and environmental economics."
    author: Zihan Zhang
    googleAnalyticsID: "UA-145837376-1"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Research","Courses","MathCamp"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    assets:
        disableScrollBarStyle: true
        theme_color: "#f8f4eb"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Zihan Zhang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 3
        ordered: false
        startLevel: 2
